### PR TITLE
WIP Rust-Python client parity

### PR DESCRIPTION
**Pull request by amoffat**
Working on making the Rust client do what the Python client does

I removed `.idea` from the `.gitignore` so that we can share our run configurations, which might be useful.  Intellij has some pretty good sharing features, if you share the `.idea` folder.

### CODE REVIEW

**Comment by adamfeuer** [comment]
@amoffat Looks like there are conflicts of some sort.

**Comment by amoffat** [comment]
@adamfeuer fixed.  Somehow the branches got messed up.

**Comment by adamfeuer** [comment]
@amoffat I'm a little unsure about sharing the `.idea` dir– but willing to try. It would be good if we can share the run configurations.

**Comment by adamfeuer** [comment]
@amoffat Re: the code, LGTM 👍

**Comment by amoffat** [comment]
Optionally we can just share the run configurations subfolder, and gitignore the rest.

**Pull request merged**
